version: '3.8'
services:
  frontend:
    container_name: frontend-container
    build:
      context: .
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
        REACT_APP_SIGNALR_HUB_URL: ${REACT_APP_SIGNALR_HUB_URL}
        REACT_APP_TITLE: ${REACT_APP_TITLE}
    ports:
      - "3000:80"
    restart: always